name: Prepare release PR workflow

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # Calls out to `changeset version`, but also runs prettier
          version: yarn release
          title: 'Release new version(s)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
