name: Prepare release PR workflow

on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Changeset PR
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          # Calls out to `changeset version`, but also runs prettier
          version: yarn release
          title: 'Release new version(s)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
