name: 'Validate renovate.json'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'renovate.json'
  push:
    branches:
      - main
    paths:
      - 'renovate.json'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.11
        with:
          pattern: 'renovate.json'
