name: 'Renovate: Validate configuration'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'renovate.json'
  push:
    branches:
      - main
    paths:
      - 'renovate.json'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: 'renovate.json'
